In [1]:
import torch

In [2]:
# Tensor = Multi dimensional array of numbers.
# 1 D tensor = Vector
# 2D tensor = Matrix
# nD tensor = Kth order tensor


In [3]:
# Create a vector of evenly spaced values

x = torch.arange(12, dtype = torch.float32)
x

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [4]:
# Total number of elements in tensor:
x.numel()

12

In [5]:
#Shape
x.shape

torch.Size([12])

In [6]:
# Reshape a tensor

X = x.reshape(3,4)

In [7]:
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [8]:
# If you want to just fix the number of rows or columns, use x.reshape(your_reading, -1) or x.reshape( -1, your_reading)

# ZEROES in TENSOR

torch.zeros((2, 3, 4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [9]:
#TORCH ONES

torch.ones((2, 4, 5))


tensor([[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]])

In [10]:
# Creating a random tensor:
# It will have normal distribution ---> Mena = 0 & SD = 1

torch.randn(3,4)


tensor([[-0.0802,  0.9544,  1.2331,  0.1760],
        [-1.2712, -0.8645,  0.4767,  1.4415],
        [-0.3598, -0.2805,  0.7213,  0.4521]])

In [11]:
# Creating a Tensor via Python Lists ----> Needs to be same length

my_list = [[2,3,4], [45,65,7], [23,54,9]]

torch.tensor(my_list)

tensor([[ 2,  3,  4],
        [45, 65,  7],
        [23, 54,  9]])

# INDEXING & SLICING

In [12]:
print(X)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])


In [13]:
X[-1]

tensor([ 8.,  9., 10., 11.])

In [14]:
X[1:3]

tensor([[ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [15]:
X[1:]

tensor([[ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [16]:
# Modifying a tensor:

print(X[1,2])

X[1,2] = 69

print(X[1,2])
print(X)

tensor(6.)
tensor(69.)
tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5., 69.,  7.],
        [ 8.,  9., 10., 11.]])


In [17]:
X[:2, :] = 6969
X

tensor([[6969., 6969., 6969., 6969.],
        [6969., 6969., 6969., 6969.],
        [   8.,    9.,   10.,   11.]])

# Mathematical Operations

In [18]:
X

tensor([[6969., 6969., 6969., 6969.],
        [6969., 6969., 6969., 6969.],
        [   8.,    9.,   10.,   11.]])

In [19]:
# EXP
torch.exp(x)


tensor([       inf,        inf,        inf,        inf,        inf,        inf,
               inf,        inf,  2980.9580,  8103.0840, 22026.4648, 59874.1406])

In [20]:
x = torch.tensor([1.0, 2, 3, 5])
y = torch.tensor([5, 5, 5, 5])

x+y, x-y, x*y, x/y, x**y

(tensor([ 6.,  7.,  8., 10.]),
 tensor([-4., -3., -2.,  0.]),
 tensor([ 5., 10., 15., 25.]),
 tensor([0.2000, 0.4000, 0.6000, 1.0000]),
 tensor([1.0000e+00, 3.2000e+01, 2.4300e+02, 3.1250e+03]))

In [21]:
# Concatenate Tensors

X = torch.arange(12, dtype = torch.float32).reshape((3,4))
Y = torch.tensor([[200, 100, 400, 300], [10,20,30,40], [4000,3000,2000,1000]])

# Concatenate Row Wise

print(torch.cat((X, Y), dim = 0))

# COncatenate Column Wise


print(torch.cat((X, Y), dim = 1))


tensor([[0.0000e+00, 1.0000e+00, 2.0000e+00, 3.0000e+00],
        [4.0000e+00, 5.0000e+00, 6.0000e+00, 7.0000e+00],
        [8.0000e+00, 9.0000e+00, 1.0000e+01, 1.1000e+01],
        [2.0000e+02, 1.0000e+02, 4.0000e+02, 3.0000e+02],
        [1.0000e+01, 2.0000e+01, 3.0000e+01, 4.0000e+01],
        [4.0000e+03, 3.0000e+03, 2.0000e+03, 1.0000e+03]])
tensor([[0.0000e+00, 1.0000e+00, 2.0000e+00, 3.0000e+00, 2.0000e+02, 1.0000e+02,
         4.0000e+02, 3.0000e+02],
        [4.0000e+00, 5.0000e+00, 6.0000e+00, 7.0000e+00, 1.0000e+01, 2.0000e+01,
         3.0000e+01, 4.0000e+01],
        [8.0000e+00, 9.0000e+00, 1.0000e+01, 1.1000e+01, 4.0000e+03, 3.0000e+03,
         2.0000e+03, 1.0000e+03]])


In [22]:
# Scalar Equality

X==Y


tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

In [23]:
# Sum of all tensors:

X.sum()

tensor(66.)

# BROADCASTING

In [24]:
# When the sizes of two tensors is not same, we need to broadcast the data.
# 1. Expand Both arrays so that the shape becomes the same.
# 2. Perform an ekementwise operation on resulting arrays.


In [25]:
# Creating two tensors of unequal dimensions

a = torch.arange(5).reshape((-1,1))
b = torch.arange(2).reshape((1,2))

a, b

(tensor([[0],
         [1],
         [2],
         [3],
         [4]]),
 tensor([[0, 1]]))

In [26]:
a +b

tensor([[0, 1],
        [1, 2],
        [2, 3],
        [3, 4],
        [4, 5]])

In [27]:
# Pytorch creates a new memory allocation to save data.
# You don't want this to happen as this means that your memory is being eaten up.

before = id(Y)
Y = Y+X

id(Y) == before

False

In [28]:
# So you want to make updates in place.

#Z = torch.zeros_like(Y)
print('ID(X) : ', id(X))
X[:] = X+Y
print('ID(X) : ', id(X))

ID(X) :  1806536457696
ID(X) :  1806536457696


# Conversion to Other Python Objects

In [29]:
A = X.numpy()
B = torch.from_numpy(A)
type(A), type(B)

(numpy.ndarray, torch.Tensor)

In [33]:
# FOr single element Tensor, use item.

a = torch.tensor([58])
a, a.item(), float(a), int(a)

(tensor([58]), 58, 58.0, 58)

In [34]:
X ==Y

tensor([[ True, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

In [35]:
X < Y

tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

In [36]:
X > Y

tensor([[False,  True,  True,  True],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True]])

In [37]:
X

tensor([[ 200.,  102.,  404.,  306.],
        [  18.,   30.,   42.,   54.],
        [4016., 3018., 2020., 1022.]])

In [38]:
Y

tensor([[ 200.,  101.,  402.,  303.],
        [  14.,   25.,   36.,   47.],
        [4008., 3009., 2010., 1011.]])

In [42]:
new = torch.tensor([[1,2,3], [4,5,6], [7,8,9]])
new_2 = torch.arange(5,dtype = torch.float32)

new+new_2



RuntimeError: The size of tensor a (3) must match the size of tensor b (5) at non-singleton dimension 1